services:
  db:
    build:
      context: .
      dockerfile: ./db/Dockerfile.dev
    container_name: full_dev_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb
    env_file: ".env"
    volumes:
      - devdb_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devuser -d devdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: dev_backend
    ports:
      - "8000:8000"
    environment:
      ENVIRONMENT: dev
      POSTGRES_URL: postgres://devuser:devpass@full_dev_db:5432/devdb
    env_file: ".env"
    volumes:
      - ./LoreshifterBackend:/app
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: dev_frontend
    ports:
      - "8080:80"
    env_file: ".env"
    depends_on:
      backend:
        condition: service_healthy

volumes:
  devdb_data:
