FROM python:3.14

WORKDIR /code

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

COPY ./backend/pyproject.toml /code/

RUN pip install --no-cache-dir --upgrade .

COPY ./backend /code/

CMD ["pytest"]
